### ISSUE TITLE
Build with integer-simple

### ISSUE THREAD

**Issue by basvandijk** [Bodigrim/integer-logarithms#1]
Some users of `scientific` [require](https://github.com/basvandijk/scientific/issues/15#issuecomment-275234557) to build the package with `integer-simple`. After I switched to `integer-logarithms` I lost this capability.

Could you add `integer-simple` support to `integer-logarithms`? Let me know if you need help.

**Comment by phadej** [comment]
Currently building ghc with integer-simple

**Comment by basvandijk** [comment]
Ok. I'm doing the same and created a [PR for nixpkgs](https://github.com/NixOS/nixpkgs/pull/22121) in the process for getting a GHC with `integer-simple`.

**Comment by phadej** [comment]
@basvandijk there's a PR, and tests pass locally (there's no integer-simple ghc in hvr-ppa, so cannot test on travis). But it would be great to verify with a bit larger package sets. If it's not too difficult with your nix setup, it would be great!
