### ISSUE TITLE
Support GHC 8.6.1

### ISSUE THREAD

**Issue by Bodigrim** [Bodigrim/integer-logarithms#14]
GHC 8.6.1-beta1 [is available](https://mail.haskell.org/pipermail/ghc-devs/2018-August/016098.html). I've already bumped the upper bound for `base` in cabal file. 

Now we have a choice between a new revision and a new minor version. Due to c3c55ccf250254c3cd49d33a9c10d57a234f51bc my vote is for releasing a new version. @phadej what do you think about it?

**Comment by phadej** [comment]
I'll make an upload shortly.

**Comment by asr** [comment]
Blocking https://github.com/agda/agda/issues/3160.

**Comment by Bodigrim** [comment]
@phadej please upload or/and grant me maintainership on Hackage.

**Comment by phadej** [comment]
Uploaded http://hackage.haskell.org/package/integer-logarithms-1.0.2.2
