### ISSUE TITLE
newer QuickCheck

### ISSUE THREAD

**Issue by clinty** [Bodigrim/integer-logarithms#17]
Please relax upper bound on QuickCheck

**Comment by Bodigrim** [comment]
@phadej please make a new revision on hackage.

**Comment by phadej** [comment]
@clinty, may I ask why? `integer-logarithms` library doesn't depend on `QuickCheck` - the dependency is only in tests.

**Comment by clinty** [comment]
Sure.  When Debian updates QuickCheck to 2.12 this could save us the time and effort of patching out the upper bound on the testsuite.

**Comment by phadej** [comment]
@clinty who are you? Why you have to run `integer-logarithms` tests?

I'm really keen to learn about you and your constraints.

**Comment by clinty** [comment]
I am clint@debian.org .  We don't have to run integer-logarithms tests; in fact they are presently disabled.  However, it is generally advantageous for us to run the testsuites of all Haskell packages as it helps to catch issues that are only triggered with certain endianness, integer sizes, signedness, alignment, or floating-point weirdness.

**Comment by phadej** [comment]
@clinty This is very nice, I made a revision.
